#!/bin/sh -xeu

mv /etc/resolv.conf /etc/resolv.conf_
echo nameserver 1.0.0.1 >> /etc/resolv.conf

sed -Ei 's/^(Suites: )(.*)$/\1 \2 \2-security \2-updates \2-backports/' /etc/apt/sources.list.d/ubuntu.sources
dpkg --add-architecture i386
apt-get update

useradd -mp "" user
echo "user:user" | chpasswd
usermod -aG sudo user

apt-get install -y software-properties-common

add-apt-repository -y ppa:xtradeb/apps
apt-get install -y \
  linux-image-virtual \
  openssh-server \
  librecad \
  chromium firefox \
  `#`

# https://gitlab.winehq.org/wine/wine/-/wikis/Debian-Ubuntu
mkdir -pm755 /etc/apt/keyrings
wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key
wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/noble/winehq-noble.sources
apt-get update

apt-get install -y --install-recommends winehq-staging binfmt-support
cp /usr/share/doc/wine/examples/wine.desktop /usr/share/applications/ || :

apt-get purge -y snapd
apt-get purge -y apparmor blueman
apt-get purge -y amd64-microcode intel-microcode linux-firmware
apt-get purge -y apport python3-apport apport-symptoms

ldconfig -X
update-initramfs -u

rm -rf /var/lib/apt/lists/*
mv /etc/resolv.conf_ /etc/resolv.conf
